pagerank:
  lambda: 0.85
  theta: 0.6
weights:
  intent: 0.4
  diff: 0.25
  recency: 0.2
  hub: 0.1
  role: 0.05
recency_halflife_days: 45
diversity:
  mu_file: 0.15
  mu_role: 0.1
limits:
  ncand: 2000
  iters: 50
  tol: 1.0e-6
