name: "不具合: Bug Report"
description: "Day8 プロダクトの不具合を報告するテンプレート"
labels:
  - "ci:bug"
  - "needs-triage"
body:
  - type: markdown
    attributes:
      value: |
        ## 事前チェック
        - 既知の制限や未実装事項ではないかを [docs/ROADMAP_AND_SPECS.md](../../docs/ROADMAP_AND_SPECS.md) で確認してください。
        - セキュリティインシデントに該当する場合は直接メンテナへ連絡し、ここでは公開しないでください。
  - type: textarea
    id: background
    attributes:
      label: 背景
      description: いつ・どこで・誰が遭遇したかを含めて、前提条件やシナリオを記載してください。
      placeholder: "例: 2025-02-10 の本番リリース後、/reports エンドポイントで 500 が増加。"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: 再現に必要な設定や操作手順を、番号付きリストで記載してください。
      placeholder: |-
        1. 環境変数 FEATURE_FLAG_X=true で `make start` を実行
        2. `/api/v1/reports` に GET リクエストを送る
        3. レスポンスコードを確認
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待値
      description: 本来期待していた結果を具体的な値・ログ・UI 挙動で記載してください。
      placeholder: "例: 200 OK が返り、レスポンス JSON に totalCount が含まれる。"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の結果
      description: 実際に観測した挙動・ログ・スクリーンショットなどを記載してください。
      placeholder: "例: 500 Internal Server Error で `KeyError: tenant_id` が発生。"
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 影響範囲
      description: 影響を受ける利用者、頻度、業務インパクトを記載してください。
  - type: textarea
    id: verification
    attributes:
      label: 確認方法
      description: 修正後にどのような手順・指標で解消を確認するか、具体的に記載してください。
      placeholder: "例: ステージングで再現手順を実行し、APM で 5xx が消失していることを確認する。"
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: 参考情報
      description: 関連するログ、スクリーンショット、リンクなどがあれば添付してください。
