name: daily-activity-report

on:
  schedule:
    - cron: '59 14 * * *' # JST 23:59
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate daily activity report
        shell: pwsh
        env:
          REPORT_ROOT: ${{ github.workspace }}/.activity-report
          GITHUB_TOKEN: ${{ secrets.REPORT_PAT != '' && secrets.REPORT_PAT || github.token }}
        run: ./tools/daily-report.ps1

      - name: Locate report bundle
        id: bundle
        shell: pwsh
        env:
          REPORT_ROOT: ${{ github.workspace }}/.activity-report
        run: |
          $logRoot = Join-Path $env:REPORT_ROOT 'logs'
          if(-not (Test-Path $logRoot)){ throw "Report directory not found: $logRoot" }
          $latest = Get-ChildItem -Path $logRoot -Directory | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if(-not $latest){ throw "Report generation did not produce any output" }
          "report_path=$($latest.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "report_name=$($latest.Name)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload daily report artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-report-${{ steps.bundle.outputs.report_name }}
          path: ${{ steps.bundle.outputs.report_path }}
          if-no-files-found: error

# 新規プロジェクトへ組み込む際は secrets.REPORT_PAT に PAT を登録し、tools/daily-report.ps1 の ReposFull を目的のリポジトリに調整すること。
