name: pr-gate
on:
  pull_request:
defaults:
  run:
    working-directory: workflow-cookbook
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Require CODEOWNERS approval
        id: codeowners
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pull_number = context.payload.pull_request.number;
            const {data: pr} = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });

            const pendingUsers = pr.requested_reviewers?.map((reviewer) => `@${reviewer.login}`) ?? [];
            const pendingTeams = pr.requested_teams?.map(
              (team) => `@${team.organization.login}/${team.slug}`,
            ) ?? [];

            if (pendingUsers.length === 0 && pendingTeams.length === 0) {
              core.notice('All required reviewers have approved.');
              return;
            }

            const pending = [...pendingUsers, ...pendingTeams];
            core.setFailed(
              `Awaiting required review from: ${pending.join(', ')}`,
            );
      - name: Enforce governance gate
        run: python tools/ci/check_governance_gate.py
      - name: Block auto-merge (informational)
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
      - name: Fail pending CODEOWNERS approval
        if: ${{ steps.codeowners.outcome == 'failure' }}
        run: |
          echo "CODEOWNERS approval pending; marking job as failed"
          exit 1
