name: pr-gate
on:
  pull_request:
jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Require CODEOWNERS approval
        uses: mheap/github-action-required-reviewers@v2
        with:
          reviewers: 'CODEOWNERS'
          failOnMissing: true
      - name: Block auto-merge (informational)
        run: |
          echo "Auto merge is disabled by policy"
          exit 0
