name: reflection
on:
  workflow_run:
    workflows: ["test"]
    types: [completed]
  schedule:
    - cron: "0 3 * * *"   # 毎日3:00 UTC
defaults:
  run:
    working-directory: workflow-cookbook
jobs:
  reflect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Resolve artifact run id
        id: artifact-meta
        run: |
          if [ -n "${RUN_ID}" ]; then
            echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
          else
            echo "::notice title=artifact::No linked workflow_run; skip download"
          fi
        env:
          RUN_ID: ${{ github.event.workflow_run.id || '' }}
      - name: Download test logs
        if: ${{ steps.artifact-meta.outputs.run_id != '' }}
        uses: actions/download-artifact@v4
        with:
          name: test-logs
          path: workflow-cookbook/logs
          run-id: ${{ steps.artifact-meta.outputs.run_id }}
          if-no-artifact-found: warn
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Analyze logs → report
        working-directory: workflow-cookbook
        run: |
          python scripts/analyze.py
      - name: Commit report
        working-directory: workflow-cookbook
        run: |
          git config user.name "reflect-bot"
          git config user.email "bot@example.com"
          git add reports/today.md
          git commit -m "chore(report): reflection report [skip ci]" || echo "no changes"
          git push || true
      - name: Open issue if needed (draft memo)
        if: ${{ hashFiles('workflow-cookbook/reports/issue_suggestions.md') != '0' }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "反省TODO ${{ github.run_id }}"
          content-filepath: workflow-cookbook/reports/issue_suggestions.md
          labels: reflection, needs-triage
      - name: Open draft PR with doc/test tweaks (disabled)
        if: ${{ false }}  # デチューン：無効化
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Reflection suggestions (draft)"
          draft: true
          labels: reflection
